# Generated by Django 3.2.5 on 2021-07-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data_dascimento',
            new_name='data_nascimento',
        ),
    ]
